import "./globals.css";
import type { Metadata } from "next";
import Footer from "@/components/footer";
import Header from "@/components/header";
import { Playfair_Display } from "next/font/google";
import HeaderMobile from "@/components/header-mobile";
import { ThemeProvider } from "@/components/theme-provider";
import { NextIntlClientProvider } from "next-intl";

export function generateStaticParams() {
  return [{ locale: "vi" }, { locale: "en" }];
}
const playfairDisplay = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  weight: ["600", "500", "900", "400", "700"],
});

export const metadata: Metadata = {
  title: "M&D 20",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={`${playfairDisplay.className}  antialiased`}>
        <NextIntlClientProvider>
          {" "}
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
            <div className="hidden lg:block">
              <Header />
            </div>
            <div className="block lg:hidden">
              <HeaderMobile />
            </div>
            {children} <Footer />
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
